version: '3'
services:
  source:
    build:
      context: . 
      dockerfile: scst-source-Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  processor:
    build:
      context: .
      dockerfile: scst-processor-Dockerfile
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
    depends_on: 
      - kafka 
      - zookeeper 

  sink:
    build:
      context: .
      dockerfile: scst-sink-Dockerfile
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
    depends_on:
      - kafka 
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - 9092:9092
    depends_on: 
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5671:5671
      - 15671:15671
